FROM python:3.11-slim

WORKDIR /app
RUN pip install --no-cache-dir mlflow==3.7.0

EXPOSE 5002
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5002",      "--backend-store-uri", "sqlite:////mlruns/mlflow.db",      "--default-artifact-root", "/mlruns"]
