backcast_loss_ratio: 0.0
context_length: 72
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__unique_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        KNMI_260: 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 32
          - 4
          - 8
        - false
        - !!binary |
          SwAAAE4AAABNAAAASQAAAF8AAAAyAAAANgAAADAAAAA=
      warn: true
    unique_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        KNMI_260: 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 32
          - 4
          - 8
        - false
        - !!binary |
          SwAAAE4AAABNAAAASQAAAF8AAAAyAAAANgAAADAAAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - unique_id
  lags: null
  max_encoder_length: 72
  max_prediction_length: 24
  min_encoder_length: 72
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - &id003 !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 24
  predict_mode: false
  randomize_length: null
  scalers: {}
  static_categoricals: null
  static_reals: null
  target: y
  target_normalizer: &id004 !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    _groups:
    - unique_id
    _method_kwargs: {}
    center: true
    groups:
    - unique_id
    method: standard
    method_kwargs: {}
    missing_:
      center: 10.896485328674316
      scale: 6.811906337738037
    norm_: !!python/object:pandas.core.frame.DataFrame
      _flags:
        allows_duplicate_labels: true
      _metadata: []
      _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
      - !!python/tuple
        - !!python/object/apply:pandas._libs.internals._unpickle_block
          - !!python/object/apply:numpy._core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
              - 1
            - !!python/object/apply:numpy.dtype
              args:
              - f4
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AVguQSP72UA=
          - !!python/object/apply:builtins.slice
            - 0
            - 2
            - 1
          - 2
      - - !!python/object/apply:pandas.core.indexes.base._new_Index
          - &id002 !!python/name:pandas.core.indexes.base.Index ''
          - data: !!python/object/apply:numpy._core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 2
              - !!python/object/apply:numpy.dtype
                args:
                - O8
                - false
                - true
                state: !!python/tuple
                - 3
                - '|'
                - null
                - null
                - null
                - -1
                - -1
                - 63
              - false
              - - center
                - scale
            name: null
        - !!python/object/apply:pandas.core.indexes.base._new_Index
          - *id002
          - data: !!python/object/apply:numpy._core.multiarray._reconstruct
              args:
              - *id001
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 1
              - *id003
              - false
              - !!binary |
                AAAAAAAAAAA=
            name: unique_id
      _typ: dataframe
      attrs: {}
    scale_by_group: false
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals: []
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - y
  variable_groups: null
  weight: null
dropout: 0.1
expansion_coefficient_lengths:
- 3
- 7
learning_rate: 0.003
log_gradient_flow: false
log_interval: 10
log_val_interval: 1
monotone_constraints: {}
num_block_layers:
- 3
- 3
num_blocks:
- 3
- 3
optimizer: adam
optimizer_params: null
output_transformer: *id004
prediction_length: 24
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
sharing:
- true
- true
stack_types:
- trend
- seasonality
weight_decay: 0.01
widths:
- 256
- 256
